- pom.xml
- src/main/java/com/shinhan/soloplay/raid/ParticipantEntity.java
- src/main/java/com/shinhan/soloplay/raid/ParticipantId.java
- src/main/java/com/shinhan/soloplay/raid/RaidController.java
- src/main/java/com/shinhan/soloplay/raid/RaidEntity.java
- src/main/java/com/shinhan/soloplay/raid/RaidRepository.java
- src/main/java/com/shinhan/soloplay/raid/RaidService.java
- src/main/java/com/shinhan/soloplay/raid/RaidServiceImpl.java
- src/main/resources/application.properties
> [Feat] 레이드, 참가자 엔티티

- .gitignore
- src/main/resources/application.properties
> Feat mainpage

- src/main/java/com/shinhan/soloplay/coupon/CouponController.java
- src/main/java/com/shinhan/soloplay/coupon/CouponEntity.java
- src/main/java/com/shinhan/soloplay/coupon/CouponRepository.java
- src/main/java/com/shinhan/soloplay/coupon/CouponService.java
- src/main/java/com/shinhan/soloplay/coupon/CouponServiceImpl.java
- src/main/java/com/shinhan/soloplay/point/PointController.java
- src/main/java/com/shinhan/soloplay/point/PointEntity.java
- src/main/java/com/shinhan/soloplay/point/PointRepository.java
- src/main/java/com/shinhan/soloplay/point/PointService.java
- src/main/java/com/shinhan/soloplay/point/PointServiceImpl.java
[Feat] 포인트 CRUD #6
- 포인트 엔티티, 컨트롤러, 서비스
-
> [Feat] 쿠폰, 포인트 엔티티

- src/main/java/com/shinhan/soloplay/coupon/CouponEntity.java
[Feat] 쿠폰 엔티티 구현 #21
- 엔티티 수정했습니다
-
> [Feat] 쿠폰 엔티티 수정

- src/main/java/com/shinhan/soloplay/coupon/CouponHistoryEntity.java
- src/main/java/com/shinhan/soloplay/point/PointEntity.java
> [Feat] id 추가,coupon history추가

- src/main/resources/templates/test.html
- auth -> user pakage변경
- auth -> user entity 이름 변경 및 비밀번호 변수 변경
> 🌟(#5) [Feat] 유저 패키지 생성 및 비밀번호 변수 변경 

- src/main/java/com/shinhan/soloplay/theme/ThemeController.java
- ThemeSearchController -> ThemeController 명칭 수정
> [Fix] ThemeSearchController -> ThemeController 명칭 수정

- src/main/java/com/shinhan/soloplay/merchant/MerchantEntity.java
- src/main/java/com/shinhan/soloplay/theme/ThemeEntity.java
> 🌟(#5) [Fix] 가맹점 엔티티 에러 수정 

- src/main/java/com/shinhan/soloplay/raid/RaidController.java
- src/main/java/com/shinhan/soloplay/raid/RaidDTO.java
- src/main/java/com/shinhan/soloplay/raid/RaidEntity.java
> 🌟(#9) [Feat] 레이드 컨트롤러 대미지 계산식 추가

- src/main/java/com/shinhan/soloplay/coupon/CouponHistoryEntity.java
- src/main/java/com/shinhan/soloplay/point/PointEntity.java
- pointName 칼럼 추가
- ManyToOne 추가
> 🌟(#6) [Fix] point 엔티티 수정

- src/main/java/com/shinhan/soloplay/coupon/CouponEntity.java
- src/main/java/com/shinhan/soloplay/point/PointEntity.java
> 🌟(#6) [Fix]엔티티 수정

- src/main/java/com/shinhan/soloplay/merchant/MerchantEntity.java
- src/main/java/com/shinhan/soloplay/merchant/MerchantRepository.java
- src/main/java/com/shinhan/soloplay/merchant/MerchantService.java
- src/main/java/com/shinhan/soloplay/merchant/MerchantServiceImpl.java
- src/main/java/com/shinhan/soloplay/point/PointEntity.java
- src/main/java/com/shinhan/soloplay/user/UserEntity.java
- src/main/java/com/shinhan/soloplay/user/UserRepository.java
- src/main/java/com/shinhan/soloplay/user/UserServcieImpl.java
- src/main/java/com/shinhan/soloplay/user/UserService.java
> 🌟(#2) 유저 및 가맹점 리포 및 서비스 제작 

- src/main/java/com/shinhan/soloplay/card/UserCardEntity.java
- src/main/java/com/shinhan/soloplay/coupon/CouponEntity.java
- src/main/java/com/shinhan/soloplay/participant/ParticipantId.java
- src/main/java/com/shinhan/soloplay/participant/ParticipantRepository.java
- src/main/java/com/shinhan/soloplay/theme/MainCategoryEntity.java
- src/main/java/com/shinhan/soloplay/theme/SubCategoryEntity.java
- src/main/java/com/shinhan/soloplay/theme/ThemeContentEntity.java
- src/main/java/com/shinhan/soloplay/theme/ThemeEntity.java
> 🌟(#10) [Fix] 전체적으로 자잘한 오류 수정

- src/main/java/com/shinhan/soloplay/card/CardUsageHistoryRepository.java
- src/main/java/com/shinhan/soloplay/participant/ParticipantDTO.java
- src/main/java/com/shinhan/soloplay/participant/ParticipantEntity.java
- src/main/java/com/shinhan/soloplay/participant/ParticipantId.java
- src/main/java/com/shinhan/soloplay/participant/ParticipantRepository.java
- src/main/java/com/shinhan/soloplay/participant/ParticipantService.java
- src/main/java/com/shinhan/soloplay/participant/ParticipantServiceImpl.java
- src/main/java/com/shinhan/soloplay/raid/RaidController.java
- 레이드 참가(카드사용내역 이슈 있어서 미완성)
- 레이드 결과 출력 백엔드 완성
- 카드사용내역 레포지토리 파일만 만들어둠
> [Feat] 레이드 참가 및 결과, 카드사용내역 레포지토리

- src/main/java/com/shinhan/soloplay/raid/RaidEntity.java
[Fix] Raid Merchant 관계 일대일에서 일대다로 수정
> [Fix] Raid Merchant 관계 일대일에서 일대다로 수정

- src/main/java/com/shinhan/soloplay/card/CardUsageHistoryEntity.java
- src/main/java/com/shinhan/soloplay/card/CardUsageHistoryRepository.java
- src/main/java/com/shinhan/soloplay/coupon/CouponEntity.java
- CouponEntity 중복 칼럼 제거
- CardUsageHistoryEntity transaction_time 타입 timestamp로 수정
> [Fix] CouponEntity 중복 칼럼 제거 및 CardUsageHistoryEntity 수정

- .gitignore
- src/main/java/com/shinhan/soloplay/card/CardUsageHistoryEntity.java
- src/main/java/com/shinhan/soloplay/card/CardUsageHistoryRepository.java
- src/main/java/com/shinhan/soloplay/participant/ParticipantRepository.java
- src/main/java/com/shinhan/soloplay/participant/ParticipantService.java
- src/main/java/com/shinhan/soloplay/participant/ParticipantServiceImpl.java
- src/main/java/com/shinhan/soloplay/raid/RaidController.java
- 레이드 참가 구현
- 레이드 내역 조회 구현
- 레이드 공격력 계산 구현
- cardUsageEntity 문제 사항 수정
> 🌟(#9) [Feat, Fix] 레이드 전투 구현, cardUsageEntity 수정

- src/main/java/com/shinhan/soloplay/auth/AuthController.java
- src/main/java/com/shinhan/soloplay/auth/AuthDTO.java
- src/main/java/com/shinhan/soloplay/auth/AuthService.java
- src/main/java/com/shinhan/soloplay/config/SecurityConfig.java
- src/main/java/com/shinhan/soloplay/config/WebConfig.java
- src/main/java/com/shinhan/soloplay/merchant/MerchantEntity.java
- src/main/java/com/shinhan/soloplay/user/UserDTO.java
- src/main/java/com/shinhan/soloplay/user/UserEntity.java
- 로그인 Security 구현
- 회원가입 구현
- RestAPI 형식으로 front로 return
- Security Config 설정, 현 개발 환경으로 모든 요청에 대해 인가
> 🌟(#2) 로그인 및 회원가입 ,Security cors config 

- src/main/java/com/shinhan/soloplay/merchant/MerchantDTO.java
- src/main/java/com/shinhan/soloplay/merchant/MerchantEntity.java
- src/main/java/com/shinhan/soloplay/merchant/MerchantService.java
- src/main/java/com/shinhan/soloplay/merchant/MerchantServiceImpl.java
- src/main/java/com/shinhan/soloplay/raid/RaidController2.java
- src/main/java/com/shinhan/soloplay/raid/RaidDTO.java
- src/main/java/com/shinhan/soloplay/raid/RaidRepository.java
- src/main/java/com/shinhan/soloplay/raid/RaidService.java
- src/main/java/com/shinhan/soloplay/raid/RaidServiceImpl.java
-레이드&가맹점 dto, entity 수정
-진행중인 레이드 데이터 조회 및 리턴
> 🌟(#7) [Feat] 진행중인 레이드 조회CRUD 구현

- src/main/java/com/shinhan/soloplay/card/CardUsageHistoryServiceImpl.java
- src/main/java/com/shinhan/soloplay/theme/MainCategoryRepositoryYJ.java
- src/main/java/com/shinhan/soloplay/theme/MainCategoryServiceImplYJ.java
- [Fix] CardUsageHistory DTO수정
> 🌟(#16) [Fix] CardUsageHistory DTO수정

- src/main/java/com/shinhan/soloplay/participant/ParticipantServiceImpl.java
> [Chore] ParticipantServiceImpl 정상화

- pom.xml
- src/main/java/com/shinhan/soloplay/user/UserController.java
- src/main/java/com/shinhan/soloplay/user/UserServcieImpl.java
> 🌟(#2) [Feat] Swagger 적용 

- src/main/java/com/shinhan/soloplay/auth/AuthController.java
- src/main/java/com/shinhan/soloplay/auth/AuthDTO.java
- src/main/java/com/shinhan/soloplay/auth/AuthService.java
- src/main/java/com/shinhan/soloplay/user/UserDTO.java
- src/main/java/com/shinhan/soloplay/user/UserEntity.java
> 🌟(#2) 로그인 회원가입 예외처리 

- src/main/java/com/shinhan/soloplay/card/CardController.java
- src/main/java/com/shinhan/soloplay/card/CardService.java
- src/main/java/com/shinhan/soloplay/card/CardServiceImpl.java
- src/main/java/com/shinhan/soloplay/card/CardUsageHistoryDTO.java
- src/main/java/com/shinhan/soloplay/card/CardUsageHistoryRepository.java
- src/main/java/com/shinhan/soloplay/card/CardUsageHistoryServiceImpl.java
- src/main/java/com/shinhan/soloplay/card/UserCardDTO.java
- src/main/java/com/shinhan/soloplay/card/UserCardRepository.java
- src/main/java/com/shinhan/soloplay/card/UserCardServiceImpl.java
- src/main/java/com/shinhan/soloplay/participant/ParticipantServiceImpl.java
> 🌟(#16) 카드목록, 카드내역 수정

- src/main/java/com/shinhan/soloplay/coupon/CouponHistoryEntity.java
- src/main/java/com/shinhan/soloplay/point/PointController.java
- src/main/java/com/shinhan/soloplay/point/PointDTO.java
- src/main/java/com/shinhan/soloplay/point/PointEntity.java
- src/main/java/com/shinhan/soloplay/point/PointRepository.java
- src/main/java/com/shinhan/soloplay/point/PointService.java
- src/main/java/com/shinhan/soloplay/point/PointServiceImpl.java
> 🌟(#6 ) [Feat]point CRUD

- src/main/java/com/shinhan/soloplay/theme/BucketListRequestDTO.java
- src/main/java/com/shinhan/soloplay/theme/OpenAIController.java
- src/main/java/com/shinhan/soloplay/theme/OpenAIRequestDTO.java
- src/main/java/com/shinhan/soloplay/theme/OpenAIResponseDTO.java
- src/main/java/com/shinhan/soloplay/theme/OpenAIService.java
- src/main/java/com/shinhan/soloplay/theme/SubCategoryDTO.java
- src/main/java/com/shinhan/soloplay/theme/ThemeRepositoryJK.java
- src/main/java/com/shinhan/soloplay/theme/ThemeResponseDTO.java
- src/main/java/com/shinhan/soloplay/theme/ThemeServiceJK.java
> 🌟(#4) 입력받은 버킷리스트를 GPT API로 테마 대분류, 소분류 받기

- src/main/java/com/shinhan/soloplay/participant/ParticipantEntity.java
- src/main/java/com/shinhan/soloplay/participant/ParticipantRepository.java
- src/main/java/com/shinhan/soloplay/participant/ParticipantService.java
- src/main/java/com/shinhan/soloplay/participant/ParticipantServiceImpl.java
- src/main/java/com/shinhan/soloplay/raid/BattleResponseDTO.java
- src/main/java/com/shinhan/soloplay/raid/RaidController.java
> 🌟(#9) [Feat] 레이드 배틀 필요 데이터 전송 구현

- src/main/java/com/shinhan/soloplay/theme/MainCategoryController.java
- src/main/java/com/shinhan/soloplay/theme/MainCategoryDTO.java
- src/main/java/com/shinhan/soloplay/theme/OpenAIController.java
- src/main/java/com/shinhan/soloplay/theme/OpenAIService.java
- src/main/java/com/shinhan/soloplay/theme/SubCategoriesDTO.java
- src/main/java/com/shinhan/soloplay/theme/ThemeRepositoryJK.java
- src/main/java/com/shinhan/soloplay/theme/ThemeServiceJK.java
- GPT 질문 수정
- 소분류 테마를 위한 DTO, Service, Controller 구성
> 🌟(#4) [Feat] GPT API 질문 수정 및 테마 등록을 위한 대분류, 소분류 테마 선별 가능하게 하기 진행중

- src/main/java/com/shinhan/soloplay/merchant/MerchantEntity.java
- src/main/java/com/shinhan/soloplay/theme/SubCategoryEntity.java
- src/main/java/com/shinhan/soloplay/theme/ThemeContentEntity.java
- src/main/java/com/shinhan/soloplay/theme/ThemeController.java
- src/main/java/com/shinhan/soloplay/theme/ThemeEntity.java
- src/main/java/com/shinhan/soloplay/theme/ThemeRegisterDTO1.java
- src/main/java/com/shinhan/soloplay/theme/ThemeRepository1.java
- src/main/java/com/shinhan/soloplay/theme/ThemeSearchDTO1.java
- src/main/java/com/shinhan/soloplay/theme/ThemeService1.java
- src/main/java/com/shinhan/soloplay/theme/ThemeServiceImpl1.java
- src/main/java/com/shinhan/soloplay/user/UserEntity.java
- Theme Controller, Service, ServiceImpl, Repository 구조 구성 완료
- JPA 로 구성했던 부분을 전부 JPQL로 전환하는 작업 진행 중 (Theme ServiceImpl, Repository 수정 중) / 서버시작 오류 발생으로 인한 임시데이터 구성
> 🌟(#8) [Feat] Theme CRUD를 위한 전반적인 작업 진행 

- src/main/java/com/shinhan/soloplay/participant/ParticipantEntity.java
- src/main/java/com/shinhan/soloplay/participant/ParticipantRepository.java
- src/main/java/com/shinhan/soloplay/participant/ParticipantService.java
- src/main/java/com/shinhan/soloplay/participant/ParticipantServiceImpl.java
- src/main/java/com/shinhan/soloplay/raid/BattleResponseDTO.java
- src/main/java/com/shinhan/soloplay/raid/RaidController.java
- src/main/java/com/shinhan/soloplay/raid/RaidEntity.java
- src/main/java/com/shinhan/soloplay/raid/RaidRewardRequestDTO.java
- 레이드 로직은 DB에서 트리거와 프로시저로 구현
- 보상 받기는 따로 클릭으로 하도록 구현
> 🌟(#9) [Feat] 레이드 완료 및 보상 구현

- src/main/java/com/shinhan/soloplay/coupon/CouponController.java
- src/main/java/com/shinhan/soloplay/coupon/CouponRepository.java
- src/main/java/com/shinhan/soloplay/coupon/CouponService.java
- src/main/java/com/shinhan/soloplay/coupon/CouponServiceImpl.java
- src/main/java/com/shinhan/soloplay/coupon/CouponWithDetailsDTO.java
- src/main/java/com/shinhan/soloplay/point/PointController.java
- src/main/java/com/shinhan/soloplay/point/PointService.java
- src/main/java/com/shinhan/soloplay/point/PointServiceImpl.java
> 🌟(#21) coupon 조회, couponId별 재조회 

- src/main/java/com/shinhan/soloplay/point/PointController.java
- src/main/java/com/shinhan/soloplay/point/PointService.java
- src/main/java/com/shinhan/soloplay/point/PointServiceImpl.java
> 🌟(#6) [Fix] 포인트 총합 음수 제외

- pom.xml
- src/main/java/com/shinhan/soloplay/card/CardController.java
> 🌟(#16) [Fix] 카드목록

- src/main/java/com/shinhan/soloplay/theme/ThemeController.java
- src/main/java/com/shinhan/soloplay/theme/ThemeEntity.java
- src/main/java/com/shinhan/soloplay/theme/ThemeRepository1.java
- src/main/java/com/shinhan/soloplay/theme/ThemeSearchDTO1.java
- src/main/java/com/shinhan/soloplay/theme/ThemeService1.java
- src/main/java/com/shinhan/soloplay/theme/ThemeServiceImpl1.java
- 테마 전체조회 DB연결 및 프론트엔드 연결 완료 / 필터검색, 나의 테마조회는 추가 구현 필요
- 테마 상세조회 DB연결 및 프론트엔드 연결 완료 / 나의 테마조회는 추가 구현 필요
> 🌟(#8) [Feat] themeSearch, themeDetail 조회 DB연동 및 FrontEnd 연결 진행

- pom.xml
- src/main/java/com/shinhan/soloplay/auth/AuthController.java
- src/main/java/com/shinhan/soloplay/config/SecurityConfig.java
- src/main/java/com/shinhan/soloplay/config/WebConfig.java
> 🌟(#2) 로그인시 세션 수정 , 

- src/main/java/com/shinhan/soloplay/coupon/CouponController.java
- src/main/java/com/shinhan/soloplay/point/PointController.java
- src/main/java/com/shinhan/soloplay/point/PointService.java
- src/main/java/com/shinhan/soloplay/point/PointServiceImpl.java
> 🌟(#6) [Fix] 포인트/ 쿠폰 세션 아이디 가져오기

- src/main/java/com/shinhan/soloplay/raid/RaidController.java
> 🌟(#9) [Fix] 유저 정보 받기 정상화, 레이드 정보 받기

- src/main/java/com/shinhan/soloplay/raid/RaidController2.java
- src/main/java/com/shinhan/soloplay/raid/RaidDTO.java
- src/main/java/com/shinhan/soloplay/raid/RaidService.java
- 레이드 진행 상태 추가
- user_id session에서 가져오는 걸로 변경
> 🌟(#69) [Fix] 레이드 진행 상태 변경

- src/main/java/com/shinhan/soloplay/theme/OpenAIService.java
- GPT의 결과 값이 무조건 단어로만 불러올 수 있게 하고, 어투를 친근하게 바꿈
-
> 🌟(#4) [Fix] GPT API 명령어 수정

- src/main/java/com/shinhan/soloplay/theme/ThemeController.java
- src/main/java/com/shinhan/soloplay/theme/ThemeRepository1.java
- src/main/java/com/shinhan/soloplay/theme/ThemeService1.java
- src/main/java/com/shinhan/soloplay/theme/ThemeServiceImpl1.java
- MyThemeDetail 내부에 수정기능 구현 진행하기 위한 코드점검 완료
-
> 🌟(#8) [Feat][Fix] MyThemeDetail 수정하기 기능 추가 및 수정

- src/main/java/com/shinhan/soloplay/card/CardController.java
> 🌟(#16)[Feat] 세션

- src/main/java/com/shinhan/soloplay/auth/AuthController.java
> 🌟(#2) [Fix] Login error 수정 

- src/main/java/com/shinhan/soloplay/auth/AuthController.java
> [Fix] login Error

- src/main/java/com/shinhan/soloplay/coupon/CouponController.java
- src/main/java/com/shinhan/soloplay/coupon/CouponIssueRequestDTO.java
- src/main/java/com/shinhan/soloplay/theme/ThemeContentRepositoryJS.java
- src/main/java/com/shinhan/soloplay/theme/ThemeEntity.java
- src/main/java/com/shinhan/soloplay/theme/ThemeRepository1.java
- src/main/java/com/shinhan/soloplay/theme/ThemeService1.java
- src/main/java/com/shinhan/soloplay/theme/ThemeServiceImpl1.java
- 테마 달성 시 쿠폰 발급
- 확인을 위해 theme에 칼럼 추가
> [Feat] 테마 달성 시 쿠폰 발급

- src/main/java/com/shinhan/soloplay/coupon/CouponController.java
- src/main/java/com/shinhan/soloplay/coupon/CouponService.java
- src/main/java/com/shinhan/soloplay/coupon/CouponServiceImpl.java
- src/main/java/com/shinhan/soloplay/point/PointController.java
- src/main/java/com/shinhan/soloplay/point/PointService.java
- src/main/java/com/shinhan/soloplay/point/PointServiceImpl.java
- src/main/java/com/shinhan/soloplay/theme/PointRewardDTO.java
- src/main/java/com/shinhan/soloplay/theme/ThemeContentEntity.java
- src/main/java/com/shinhan/soloplay/theme/ThemeContentRepository.java
- src/main/java/com/shinhan/soloplay/theme/ThemeController.java
- src/main/java/com/shinhan/soloplay/theme/ThemeService1.java
- src/main/java/com/shinhan/soloplay/theme/ThemeServiceImpl1.java
> 🌟(#6) [Fix]랜덤 포인트, 쿠폰 발급 수정

- src/main/java/com/shinhan/soloplay/theme/ThemeControllerJK.java
- src/main/java/com/shinhan/soloplay/theme/ThemeServiceImplJK.java
- src/main/java/com/shinhan/soloplay/theme/ThemeServiceJK.java
> 🌟(#4) [Fix] 정책 중 오류 수정

- src/main/java/com/shinhan/soloplay/config/SecurityConfig.java
- src/main/java/com/shinhan/soloplay/theme/ThemeContentsResponseDTO.java
- src/main/java/com/shinhan/soloplay/theme/ThemeController.java
- src/main/java/com/shinhan/soloplay/theme/ThemeControllerJK.java
- src/main/java/com/shinhan/soloplay/theme/ThemeDetailResponseDTO.java
- src/main/java/com/shinhan/soloplay/theme/ThemeRepositoryJK.java
- src/main/java/com/shinhan/soloplay/theme/ThemeService1.java
- src/main/java/com/shinhan/soloplay/theme/ThemeServiceImpl1.java
- src/main/java/com/shinhan/soloplay/theme/ThemeServiceImplJK.java
- src/main/java/com/shinhan/soloplay/theme/ThemeServiceJK.java
> 🌟(#4) 정책 수정 

- src/main/java/com/shinhan/soloplay/theme/ThemeController.java
- src/main/java/com/shinhan/soloplay/theme/ThemeService1.java
- src/main/java/com/shinhan/soloplay/theme/ThemeServiceImpl1.java
- themeController, themeServiceImpl 백엔드 로직 변경
-
> 🌟(#8) [Fix] themeController, themeServiceImpl 일부 수정 (Entity -> DTO 전송방식 변경)

- src/main/java/com/shinhan/soloplay/point/PointController.java
- src/main/java/com/shinhan/soloplay/point/PointService.java
- src/main/java/com/shinhan/soloplay/point/PointServiceImpl.java
> 🌟(#6 ) 포인트 계산 조건 변경, 카테고리별 총합, 비율 계산

- src/main/java/com/shinhan/soloplay/raid/RaidController.java
> [Fix] contribution 업데이트 로직 변경

- pom.xml
CI/CD Maven build를 위해 아래의 plugin을 추가
pom.xml
<plugin>
<groupId>org.apache.maven.plugins</groupId>
<artifactId>maven-surefire-plugin</artifactId>
<version>2.19.1</version>
</plugin>
-
-
> [BuildTest] Update pom.xml

- Dockerfile
> [Feat]Create Dockerfile

- src/main/java/com/shinhan/soloplay/openAI/OpenAIService.java
> 🌟(#4) [Fix] 소분류 작대기가 안나오게 하기 1차 시도

- pom.xml
배포 확인을 위한 actuator depencency 추가
<dependency>
<groupId>org.springframework.boot</groupId>
<artifactId>spring-boot-starter-actuator</artifactId>
</dependency>
-
-
> [CI/CDTest] Update pom.xml

- src/main/java/com/shinhan/soloplay/theme/ThemeController.java
- src/main/java/com/shinhan/soloplay/theme/ThemeRepository.java
- src/main/java/com/shinhan/soloplay/theme/ThemeService.java
- src/main/java/com/shinhan/soloplay/theme/ThemeServiceImpl.java
> 🌟(#8 ) [Feat] 테마 조회 페이징 구현

- src/main/java/com/shinhan/soloplay/config/WebConfig.java
- src/main/java/com/shinhan/soloplay/openAI/OpenAIController.java
- src/main/java/com/shinhan/soloplay/raid/RaidController.java
- src/main/java/com/shinhan/soloplay/theme/ThemeControllerJK.java
> [Fix] call url Fix

- src/main/java/com/shinhan/soloplay/theme/ThemeRepository.java
> [Bugfix] 쿼리 중복 조회 제거

- src/main/java/com/shinhan/soloplay/point/PointServiceImpl.java
> [Bugfix] 포인트 수여 조건 추가

- src/main/java/com/shinhan/soloplay/point/PointServiceImpl.java
- src/main/java/com/shinhan/soloplay/theme/ThemeServiceImpl.java
- src/main/java/com/shinhan/soloplay/themecontent/ThemeContentsResponseDTO.java
> 🌟(#4) [Fix] 포인트 수정 추가
